version: "3.8"
services:
    rabbitmq3:
        container_name: "rabbitmq"
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_USER=testuser
            - RABBITMQ_DEFAULT_PASS=1234
        ports:
            - '5672:5672'
            - '15672:15672'
